services:
  game-scraper:
    build: .
    container_name: game-scraper-cron
    volumes:
      - type: bind
        source: "./data"
        target: "/app/data"
      - type: bind
        source: "./reports"
        target: "/app/reports"
    restart: unless-stopped