services:
  game-scraper:
    build: .
    container_name: game-scraper-cron
    # FLAGS CR√çTICOS para Playwright
    init: true
    ipc: host
    cap_add:
      - SYS_ADMIN
    volumes:
      - type: bind
        source: "./data"
        target: "/app/data"
      - type: bind
        source: "./reports"
        target: "/app/reports"
    restart: unless-stopped